# Generated by Django 4.0.5 on 2022-07-30 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galery', '0002_alter_art_options_alter_gallery_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prise', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Стоймость')),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_art', to='galery.art')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
