# Generated by Django 4.0.5 on 2022-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='authentication/img/avatar.jpg', max_length=250, verbose_name='Аватар'),
        ),
    ]
