# Generated by Django 4.0.5 on 2022-07-29 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-create_on']},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='gallery',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время добавления'),
            preserve_default=False,
        ),
    ]
