# Generated by Django 4.0.5 on 2022-07-30 16:57

from django.db import migrations, models
import galery.models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_alter_art_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='art',
            field=models.ImageField(upload_to=galery.models.get_g_art_url, verbose_name='Арт'),
        ),
    ]
